version: '3.7'
services:
  php:
    build: ./grav
    volumes:
      - ./grav:/srv/grav:cached
    environment:
      - COMPOSER_ARGS=
      - SITE_URL=${SITE_URL}

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - php
    volumes:
      - ./grav:/srv/grav-public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT}:80"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"
