structure:
  inline_navbar: true
  inline_pagination: true
  use_decorators: true
  html_mode: default
  use_favicon: true
  show_date: false
style:
  configuration: centered
  width: '1280'
  allowCSS: true
  allowJS: true
  stylesheet: default
  include_type: default
  image_cropping: false
  inline_navbar: 1
