title: 'Müller Rockt Köln'
default_lang: de
author:
  name: 'Michael Müller'
  email: dominik-henn@web.de
taxonomies:
  - category
  - tag
metadata:
  description: 'Michael Müller und seine fantastische Liveband'
  Keywords: 'Michael Müller, Timm Jakovatz, Christina Heidel, Viktor Zhuravskyi, Catrin Caspari'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
